# Generated by Django 2.2.1 on 2019-10-02 21:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('text_html', models.TextField(editable=False)),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(blank='True', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='group.Group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-create_date'],
                'unique_together': {('user', 'text')},
            },
        ),
    ]
